[package]
name = "gecko_audio_ctrl"
version = "0.1.0"
authors = ["david <git@david-wilkening.de>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"